# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# slugify = lambda x: re.sub('[^a-z0-9]+', '_', x.lower())
# file template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires sqlAlchemy>=1.10.9
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the filter during the 'revision' command, regardless of autogenerate
# revision_filter = bidirectional

# set to 'true' to allow .pyc and .pyo files without a source .py file
# sourceless = false

# version location specification; This defaults to migrations/versions.  When using
# version locations, the location can use a full path to a particular version
# file or a prefix with a wildcard (e.g. migrations/versions/myproj_*).
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# version path separator; As mentioned above, it can be a separator based on OS can be one of:
# / (posix)
# \ (windows)
# . (windows on non-posix)
# If the path separator is a prefix with a wildcard (e.g. migrations/versions/*) then it
# will be replaced with the first wildcard (e.g. migrations/versions/%(rev)s_*)
# version_separator = _

# the output encoding used when revision messages from revision scripts are written to the log.
# The default is 'utf-8'.
# revision_environment = false

# set to 'true' to allow revision to be written in a single line instead of the regular format
# single_line = false

# The number of entries to output at a time when using --process to stream log output.
# streaming = false

# Disable autocomplete
# autocommit = off

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

# URL for connecting to the database.
# If a separate file is used, then the file can be version controlled.
# SQLALCHEMY_URL can also alternatively be set via environment variable:
# DATABASE_URL=postgresql://user:pass@localhost/dbname
[db]
# +postgresql://user:pass@localhost/leak_data
sqlalchemy.url = postgresql://postgres:postgres@localhost/leak_data

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail on how to write a post_write_hook function.
# hooks = myproject.util.my_post_write_hook
# hooks_raw = true
