"""
DossierParser - strict implementation according to the detailed specification.

This parser is designed to be deterministic and maximize structured data extraction
from report files generated by the specific OSINT/dossier aggregation system.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional
from uuid import uuid4

from .dossier_models import ParsedReport, ParsedPerson
from .normalization import (
    normalize_phone, normalize_date, normalize_datetime, normalize_fio,
    normalize_inn, normalize_snils, normalize_passport,
)


SECTION_HEADERS = [
    "ПРОФИЛЬ",
    "ВСЕ НАЙДЕННЫЕ ЗНАЧЕНИЯ",
    "ПРОФИЛИ",
    "БАНКИ",
    "ДОКУМЕНТЫ",
    "ВОЗМОЖНЫЕ СВЯЗИ",
    "МЕСТО РАБОТЫ",
    "АДРЕСА",
    "САЙТЫ, ГДЕ НАЙДЕНЫ РЕГИСТРАЦИИ",
    "ПЕРЕСЕЧЕНИЯ ГРАНИЦЫ",
    "ИСТОЧНИКИ",
]

SECTION_SPLIT_PATTERN = r"────────────────────────────────────────────────────────────────────────"


class DossierParser:
    """Main parser class following the exact specification."""

    def __init__(self, strict: bool = True):
        self.strict = strict
        self.warnings: list[str] = []

    def parse_file(self, path: Path | str) -> ParsedReport:
        """Parse a single report file."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(path)

        content = path.read_text(encoding="utf-8")

        return self.parse_text(content, filename=path.name)

    def parse_text(self, content: str, filename: str = "unknown.txt") -> ParsedReport:
        """Parse raw text content of a report."""
        self.warnings = []

        # 1. Parse header
        header = self._parse_header(content)

        # 2. Split into sections
        sections = self._split_into_sections(content)

        # 3. Parse main person from header + ПРОФИЛЬ / ВСЕ НАЙДЕННЫЕ ЗНАЧЕНИЯ
        main_person = self._parse_main_person(header, sections)

        # 4. Parse individual sections
        profile = self._parse_profile_section(sections.get("ПРОФИЛЬ", "") + "\n" + sections.get("БАНКИ", ""))
        documents = self._parse_documents_section(sections.get("ДОКУМЕНТЫ", ""))
        addresses = self._parse_addresses_section(sections.get("АДРЕСА", ""))
        employments = self._parse_employments_section(sections.get("МЕСТО РАБОТЫ", ""))
        connections = self._parse_connections_section(sections.get("ВОЗМОЖНЫЕ СВЯЗИ", ""))
        border_events = self._parse_border_events(sections.get("ПЕРЕСЕЧЕНИЯ ГРАНИЦЫ", ""))
        websites = self._parse_websites_section(sections.get("САЙТЫ, ГДЕ НАЙДЕНЫ РЕГИСТРАЦИИ", ""))
        source_findings = self._parse_sources_section(sections.get("ИСТОЧНИКИ", ""))

        report = ParsedReport(
            filename=filename,
            report_date=header.get("report_date"),
            sources_count=header.get("sources_count", 0),
            records_count=header.get("records_count", 0),
            main_person=main_person,
            profile_section=profile,
            documents=documents,
            addresses=addresses,
            employments=employments,
            connections=connections,
            border_events=border_events,
            websites=websites,
            source_findings=source_findings,
            warnings=self.warnings,
        )

        return report

    # ==================== HEADER ====================

    def _parse_header(self, content: str) -> dict:
        lines = content.splitlines()[:10]
        result = {}

        full_text = "\n".join(lines)

        # Main FIO from "ОТЧЁТ:" line
        m = re.search(r"ОТЧЁТ:\s*(.+?)(?:\n|$)", full_text, re.IGNORECASE)
        if m:
            result["main_fio_raw"] = m.group(1).strip()

        # Report date
        m = re.search(r"Дата:\s*([0-9.: ]+)", full_text)
        if m:
            result["report_date"] = normalize_datetime(m.group(1).strip())

        # Sources and Records count
        m = re.search(r"Источников:\s*(\d+)", full_text)
        if m:
            result["sources_count"] = int(m.group(1))

        m = re.search(r"Записей:\s*(\d+)", full_text)
        if m:
            result["records_count"] = int(m.group(1))

        return result

    # ==================== SECTION SPLITTING ====================

    def _split_into_sections(self, content: str) -> dict[str, str]:
        """Split content by the exact section headers defined in the spec."""
        sections: dict[str, str] = {}
        current_section = "HEADER"
        buffer: list[str] = []

        lines = content.splitlines(keepends=True)

        for line in lines:
            stripped = line.strip()

            # Check if this line is a section header
            matched_section = None
            for header in SECTION_HEADERS:
                if stripped.upper().startswith(header):
                    matched_section = header
                    break

            if matched_section:
                # Save previous section
                if buffer:
                    sections[current_section] = "".join(buffer)
                buffer = []
                current_section = matched_section
            else:
                buffer.append(line)

        # Save last section
        if buffer:
            sections[current_section] = "".join(buffer)

        return sections

    # ==================== SECTION PARSERS (stubs to be expanded) ====================

    def _parse_main_person(self, header: dict, sections: dict) -> ParsedPerson:
        # Very basic implementation for now - will be expanded
        fio = header.get("main_fio_raw", "Unknown")
        fio = normalize_fio(fio)

        birth_date = None
        if "birth" in str(sections.get("ПРОФИЛЬ", "")).lower():
            # TODO: proper extraction
            pass

        return ParsedPerson(fio=fio, birth_date=birth_date)

    def _parse_profile_section(self, content: str) -> dict:
        # TODO: full implementation for ПРОФИЛЬ + БАНКИ
        return {"raw": content[:2000]}

    def _parse_documents_section(self, content: str) -> list[dict]:
        # TODO: full recursive parser for ДОКУМЕНТЫ
        return []

    def _parse_addresses_section(self, content: str) -> list[dict]:
        return []

    def _parse_employments_section(self, content: str) -> list[dict]:
        return []

    def _parse_connections_section(self, content: str) -> list[dict]:
        return []

    def _parse_border_events(self, content: str) -> list[dict]:
        return []

    def _parse_websites_section(self, content: str) -> list[str]:
        return []

    def _parse_sources_section(self, content: str) -> list[dict]:
        """
        Parse ИСТОЧНИКИ section according to spec:
        - Blocks start with "▼ Название источника (записей: N)"
        - Individual records inside are separated by long strings of middle dots (·)
        """
        findings: list[dict] = []

        if not content or "ИСТОЧНИКИ" not in content:
            return findings

        # Split by source headers
        source_blocks = re.split(r"\n(?=▼\s)", content)

        for block in source_blocks:
            if not block.strip().startswith("▼"):
                continue

            # Extract source name
            header_match = re.match(r"▼\s*(.+?)(?:\n|$)", block)
            source_name = header_match.group(1).strip() if header_match else "Unknown Source"

            # Split records by middle dot separator (U+00B7)
            record_separator = "·" * 10  # at least 10 middle dots
            records_raw = re.split(rf"\n\s*{record_separator}.*\n", block)

            for idx, rec in enumerate(records_raw):
                rec = rec.strip()
                if not rec or len(rec) < 10:
                    continue

                # Simple key-value extraction for now (can be made much smarter)
                data: dict[str, str] = {}
                for line in rec.splitlines():
                    if ":" in line:
                        k, _, v = line.partition(":")
                        k = k.strip()
                        v = v.strip()
                        if k and v:
                            data[k] = v

                findings.append({
                    "source_name": source_name,
                    "record_index": idx,
                    "data": data,
                    "raw_text": rec[:2000],
                })

        return findings
