"""
DossierParser - strict implementation according to the detailed specification.

This parser is designed to be deterministic and maximize structured data extraction
from report files generated by the specific OSINT/dossier aggregation system.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional
from uuid import uuid4

from .dossier_models import ParsedReport, ParsedPerson
from .normalization import (
    normalize_phone, normalize_date, normalize_datetime, normalize_fio,
    normalize_inn, normalize_snils, normalize_passport,
)


SECTION_HEADERS = [
    "ПРОФИЛЬ",
    "ВСЕ НАЙДЕННЫЕ ЗНАЧЕНИЯ",
    "ПРОФИЛИ",
    "БАНКИ",
    "ДОКУМЕНТЫ",
    "ВОЗМОЖНЫЕ СВЯЗИ",
    "МЕСТО РАБОТЫ",
    "АДРЕСА",
    "САЙТЫ, ГДЕ НАЙДЕНЫ РЕГИСТРАЦИИ",
    "ПЕРЕСЕЧЕНИЯ ГРАНИЦЫ",
    "ИСТОЧНИКИ",
]

SECTION_SPLIT_PATTERN = r"────────────────────────────────────────────────────────────────────────"


class DossierParser:
    """Main parser class following the exact specification."""

    def __init__(self, strict: bool = True):
        self.strict = strict
        self.warnings: list[str] = []

    def parse_file(self, path: Path | str) -> ParsedReport:
        """Parse a single report file."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(path)

        content = path.read_text(encoding="utf-8")

        return self.parse_text(content, filename=path.name)

    def parse_text(self, content: str, filename: str = "unknown.txt") -> ParsedReport:
        """Parse raw text content of a report."""
        self.warnings = []

        # 1. Parse header
        header = self._parse_header(content)

        # 2. Split into sections
        sections = self._split_into_sections(content)

        # 3. Parse main person from header + ПРОФИЛЬ / ВСЕ НАЙДЕННЫЕ ЗНАЧЕНИЯ
        main_person = self._parse_main_person(header, sections)

        # 4. Parse individual sections
        profile = self._parse_profile_section(sections.get("ПРОФИЛЬ", "") + "\n" + sections.get("БАНКИ", ""))
        documents = self._parse_documents_section(sections.get("ДОКУМЕНТЫ", ""))
        addresses = self._parse_addresses_section(sections.get("АДРЕСА", ""))
        employments = self._parse_employments_section(sections.get("МЕСТО РАБОТЫ", ""))
        connections = self._parse_connections_section(sections.get("ВОЗМОЖНЫЕ СВЯЗИ", ""))
        border_events = self._parse_border_events(sections.get("ПЕРЕСЕЧЕНИЯ ГРАНИЦЫ", ""))
        websites = self._parse_websites_section(sections.get("САЙТЫ, ГДЕ НАЙДЕНЫ РЕГИСТРАЦИИ", ""))
        source_findings = self._parse_sources_section(sections.get("ИСТОЧНИКИ", ""))

        report = ParsedReport(
            filename=filename,
            report_date=header.get("report_date"),
            sources_count=header.get("sources_count", 0),
            records_count=header.get("records_count", 0),
            main_person=main_person,
            profile_section=profile,
            documents=documents,
            addresses=addresses,
            employments=employments,
            connections=connections,
            border_events=border_events,
            websites=websites,
            source_findings=source_findings,
            warnings=self.warnings,
        )

        self._post_process(report)
        return report

    # ==================== HEADER ====================

    def _parse_header(self, content: str) -> dict:
        lines = content.splitlines()[:10]
        result = {}

        full_text = "\n".join(lines)

        # Main FIO from "ОТЧЁТ:" line
        m = re.search(r"ОТЧЁТ:\s*(.+?)(?:\n|$)", full_text, re.IGNORECASE)
        if m:
            result["main_fio_raw"] = m.group(1).strip()

        # Report date
        m = re.search(r"Дата:\s*([0-9.: ]+)", full_text)
        if m:
            result["report_date"] = normalize_datetime(m.group(1).strip())

        # Sources and Records count
        m = re.search(r"Источников:\s*(\d+)", full_text)
        if m:
            result["sources_count"] = int(m.group(1))

        m = re.search(r"Записей:\s*(\d+)", full_text)
        if m:
            result["records_count"] = int(m.group(1))

        return result

    # ==================== SECTION SPLITTING ====================

    def _split_into_sections(self, content: str) -> dict[str, str]:
        """Split content by the exact section headers defined in the spec."""
        sections: dict[str, str] = {}
        current_section = "HEADER"
        buffer: list[str] = []

        lines = content.splitlines(keepends=True)

        for line in lines:
            stripped = line.strip()

            # Check if this line is a section header
            matched_section = None
            for header in SECTION_HEADERS:
                if stripped.upper().startswith(header):
                    matched_section = header
                    break

            if matched_section:
                # Save previous section
                if buffer:
                    sections[current_section] = "".join(buffer)
                buffer = []
                current_section = matched_section
            else:
                buffer.append(line)

        # Save last section
        if buffer:
            sections[current_section] = "".join(buffer)

        return sections

    # ==================== SECTION PARSERS (stubs to be expanded) ====================

    def _parse_main_person(self, header: dict, sections: dict) -> ParsedPerson:
        fio = normalize_fio(header.get("main_fio_raw", "Unknown"))

        birth_date = None
        profile_text = sections.get("ПРОФИЛЬ", "") + sections.get("ВСЕ НАЙДЕННЫЕ ЗНАЧЕНИЯ", "")
        birth_match = re.search(r"(\d{2}\.\d{2}\.\d{4})", profile_text)
        if birth_match:
            birth_date = normalize_date(birth_match.group(1))

        person = ParsedPerson(fio=fio, birth_date=birth_date)

        # Extract from raw profile text (legacy)
        for line in profile_text.splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                k = k.strip().lower()
                v = v.strip()
                if "тел" in k or "мобильн" in k:
                    p = normalize_phone(v)
                    if p: person.phones.append(p)
                elif "email" in k or "почта" in k:
                    person.emails.append(v.lower())
                elif "инн" in k:
                    person.extra_inns.append(v)

        return person

    def _parse_profile_section(self, content: str) -> dict:
        """
        Deep parser for ПРОФИЛЬ + БАНКИ sections.
        Focuses on structured extraction from Gosuslugi/ESIA and banking data.
        """
        result: dict[str, Any] = {
            "esia": {
                "registration_date": None,
                "last_login": None,
                "account_status": None,
                "linked_phones": [],
                "linked_emails": [],
            },
            "banks": [],
            "other": {},
            "raw_sample": content[:2000] if len(content) > 2000 else content,
        }

        if not content.strip():
            return result

        lines = content.splitlines()
        current_bank = None

        bank_header_re = re.compile(r"^\s*(Банк|Банковская карта|Счет|Карта)\s*[:：]?\s*(.+?)$", re.IGNORECASE)
        esia_date_re = re.compile(r"(дата регистрации|дата создания|последний вход|дата авторизации)", re.IGNORECASE)

        for line in lines:
            stripped = line.strip()
            if not stripped or stripped.startswith("─"):
                continue

            # === BANK PARSING ===
            bank_match = bank_header_re.match(stripped)
            if bank_match:
                if current_bank:
                    result["banks"].append(current_bank)
                current_bank = {
                    "bank": bank_match.group(2).strip(),
                    "card_number_masked": None,
                    "account": None,
                    "open_date": None,
                    "details": {}
                }
                continue

            if current_bank and ":" in stripped:
                key, _, val = stripped.partition(":")
                key = key.strip()
                val = val.strip()
                key_lower = key.lower()

                current_bank["details"][key] = val

                if "карта" in key_lower or "номер карты" in key_lower:
                    current_bank["card_number_masked"] = val
                elif "счет" in key_lower:
                    current_bank["account"] = val
                elif "дата открытия" in key_lower or "дата выпуска" in key_lower:
                    current_bank["open_date"] = normalize_date(val)
                continue

            # === ESIA / PROFILE FIELDS ===
            if ":" in stripped:
                key, _, val = stripped.partition(":")
                key = key.strip()
                val = val.strip()
                key_lower = key.lower()

                if esia_date_re.search(key):
                    if "регистр" in key_lower or "создан" in key_lower:
                        result["esia"]["registration_date"] = normalize_date(val)
                    elif "последн" in key_lower or "авториз" in key_lower:
                        result["esia"]["last_login"] = normalize_datetime(val)
                    result["esia"][key] = val
                elif "есия" in key_lower or "госуслуги" in key_lower or "учетная запись" in key_lower:
                    result["esia"][key] = val
                elif "телефон" in key_lower:
                    norm = normalize_phone(val)
                    if norm:
                        result["esia"]["linked_phones"].append(norm)
                elif "email" in key_lower or "почта" in key_lower:
                    result["esia"]["linked_emails"].append(val.lower())
                else:
                    result["other"][key] = val

        if current_bank:
            result["banks"].append(current_bank)

        return result

    def _parse_documents_section(self, content: str) -> list[dict]:
        """
        Enhanced parser for ДОКУМЕНТЫ section with better pattern recognition.
        """
        documents: list[dict] = []
        if not content.strip():
            return documents

        lines = content.splitlines()
        current_doc = None

        # More robust header detection for different document types
        doc_header_re = re.compile(r"^\s*\[([^\]]+)\]\s*(.+?)$")

        # Common document type normalizer
        doc_type_map = {
            "паспорт рф": "passport_rf",
            "загран": "foreign_passport",
            "заграничный паспорт": "foreign_passport",
            "снилс": "snils",
            "инн": "inn",
            "водительское": "driver_license",
            "полис": "oms_policy",
        }

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue

            header_match = doc_header_re.match(stripped)
            if header_match:
                if current_doc:
                    documents.append(current_doc)

                raw_type = header_match.group(1).strip()
                number_part = header_match.group(2).strip()

                # Normalize document type
                doc_type_key = raw_type.lower()
                normalized_type = doc_type_map.get(doc_type_key, raw_type.lower().replace(" ", "_"))

                current_doc = {
                    "doc_type": normalized_type,
                    "doc_type_raw": raw_type,
                    "number_raw": number_part,
                    "fields": {},
                    "raw_lines": [stripped]
                }

                # Extract series and number more intelligently
                digits = re.findall(r"\d+", number_part)
                if len(digits) >= 2:
                    current_doc["series"] = digits[0]
                    current_doc["number"] = "".join(digits[1:])
                elif len(digits) == 1:
                    current_doc["number"] = digits[0]

                continue

            # Indented or continued fields
            if current_doc and (line.startswith("    ") or line.startswith("\t") or stripped.startswith("    ")):
                if ":" in stripped:
                    key, _, value = stripped.partition(":")
                    key = key.strip(" \t-")
                    value = value.strip()
                    if key:
                        current_doc["fields"][key] = value
                        current_doc["raw_lines"].append(stripped)

                        # Try to extract common structured fields
                        key_lower = key.lower()
                        if "дата выдачи" in key_lower:
                            current_doc["issue_date"] = normalize_date(value)
                        elif "кем выдан" in key_lower:
                            current_doc["issuer"] = value
                        elif "код подразделения" in key_lower or "код" in key_lower:
                            current_doc["issuer_code"] = value
                        elif "дата рождения" in key_lower:
                            current_doc["birth_place"] = value  # sometimes misused

        if current_doc:
            documents.append(current_doc)

        return documents

    def _parse_addresses_section(self, content: str) -> list[dict]:
        return []

    def _parse_employments_section(self, content: str) -> list[dict]:
        return []

    def _parse_connections_section(self, content: str) -> list[dict]:
        """
        More advanced parser for ВОЗМОЖНЫЕ СВЯЗИ.

        Extracts richer information about related persons and classifies
        connection types more precisely (including family subtypes when possible).
        """
        connections: list[dict] = []
        if not content.strip():
            return connections

        lines = content.splitlines()
        current_connection: dict[str, Any] = {}

        family_keywords = {
            "мать": "parent", "отец": "parent", "мама": "parent", "папа": "parent",
            "сын": "child", "дочь": "child",
            "супруг": "spouse", "супруга": "spouse", "муж": "spouse", "жена": "spouse",
            "брат": "sibling", "сестра": "sibling",
        }

        connection_patterns = [
            (r"^(По ФИО|Родственники|По имени)", "relative"),
            (r"^(По адресу|Сожители|По прописке)", "address_cohabitant"),
            (r"^(По билету|Попутчики|По рейсу|Авиаперелеты)", "flight_companion"),
            (r"^(По телефону|По номеру)", "phone_contact"),
            (r"^(По документу|По паспорту)", "document_match"),
            (r"^(По ИНН|По СНИЛС)", "identifier_match"),
        ]

        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue

            # Detect new connection header
            matched = False
            for pattern, default_type in connection_patterns:
                match = re.match(pattern, stripped, re.IGNORECASE)
                if match:
                    if current_connection and current_connection.get("related_fio"):
                        connections.append(current_connection)

                    related = stripped[match.end():].strip(" ·:-")

                    # Try to detect specific family relation
                    conn_type = default_type
                    for word, fam_type in family_keywords.items():
                        if word in stripped.lower():
                            conn_type = fam_type
                            break

                    current_connection = {
                        "connection_type": conn_type,
                        "related_fio": related,
                        "context": stripped,
                        "details": [],
                        "raw": stripped,
                    }
                    matched = True
                    break

            if not matched and current_connection:
                # Extract additional structured info about the related person
                if re.search(r"\d{2}\.\d{2}\.\d{4}", stripped):
                    current_connection["related_birth_date"] = normalize_date(stripped)

                if "паспорт" in stripped.lower():
                    current_connection.setdefault("related_documents", []).append(stripped)

                if stripped.startswith("·") or stripped.startswith("-") or ":" in stripped:
                    current_connection["details"].append(stripped)

        if current_connection and current_connection.get("related_fio"):
            connections.append(current_connection)

        return connections

    def _parse_border_events(self, content: str) -> list[dict]:
        """
        Significantly improved parser for ПЕРЕСЕЧЕНИЯ ГРАНИЦЫ.

        Extracts structured flight/border crossing events with:
        - Date/time
        - Flight number
        - Airline
        - Airports / direction
        - Passport used
        - Companions (if mentioned)
        """
        events: list[dict] = []
        if not content.strip():
            return events

        date_re = re.compile(r"(\d{2}\.\d{2}\.\d{4}(?:\s+\d{2}:\d{2}(?::\d{2})?)?)")
        flight_re = re.compile(r"(?:рейс|flight)\s*[:：]?\s*([A-Z0-9\-]+)", re.IGNORECASE)
        airline_re = re.compile(r"(?:авиакомпания|airline)\s*[:：]?\s*(.+?)(?:\s*\(|$)", re.IGNORECASE)

        current: dict[str, Any] = {}

        for line in content.splitlines():
            stripped = line.strip()
            if not stripped:
                continue

            # New event often starts with a date
            date_match = date_re.search(stripped)
            if date_match:
                if current and current.get("date"):
                    events.append(current)
                current = {
                    "event_type": "flight",
                    "date": normalize_datetime(date_match.group(1)),
                    "raw_lines": [stripped],
                    "details": {}
                }

            if not current:
                continue

            # Flight number
            fmatch = flight_re.search(stripped)
            if fmatch:
                current["flight_number"] = fmatch.group(1)

            # Airline
            amatch = airline_re.search(stripped)
            if amatch:
                current["airline"] = amatch.group(1).strip()

            # Passport
            if "паспорт" in stripped.lower():
                current["passport_used"] = stripped

            # Companions / poputchik - improved extraction
            if "попутчик" in stripped.lower() or "сопровождающий" in stripped.lower():
                companion = {"raw": stripped}
                # Try to extract FIO of companion
                fio_match = re.search(r"([А-ЯЁ][а-яё\-]+\s+[А-ЯЁ][а-яё\-]+(?:\s+[А-ЯЁ][а-яё\-]+)?)", stripped)
                if fio_match:
                    companion["fio"] = fio_match.group(1).strip()
                # Passport or document of companion
                if "паспорт" in stripped.lower():
                    companion["document"] = stripped
                current.setdefault("companions", []).append(companion)

            # General key:value
            if ":" in stripped:
                k, _, v = stripped.partition(":")
                current["details"][k.strip()] = v.strip()

            current["raw_lines"].append(stripped)

        if current and current.get("date"):
            events.append(current)

        return events

    def _parse_websites_section(self, content: str) -> list[str]:
        """
        Parse САЙТЫ, ГДЕ НАЙДЕНЫ РЕГИСТРАЦИИ section.
        Usually a simple list of domains/sites.
        """
        sites: list[str] = []
        if not content.strip():
            return sites

        for line in content.splitlines():
            stripped = line.strip()
            # Skip headers and empty lines
            if not stripped or stripped.startswith("САЙТЫ") or stripped.startswith("─"):
                continue
            # Basic domain-like strings
            if "." in stripped and len(stripped) > 3 and not stripped.startswith("·"):
                sites.append(stripped)

        return sites

    def _parse_sources_section(self, content: str) -> list[dict]:
        """
        Parse ИСТОЧНИКИ section according to spec:
        - Blocks start with "▼ Название источника (записей: N)"
        - Individual records inside are separated by long strings of middle dots (·)
        """
        findings: list[dict] = []

        if not content or "ИСТОЧНИКИ" not in content:
            return findings

        # Split by source headers
        source_blocks = re.split(r"\n(?=▼\s)", content)

        for block in source_blocks:
            if not block.strip().startswith("▼"):
                continue

            # Extract source name
            header_match = re.match(r"▼\s*(.+?)(?:\n|$)", block)
            source_name = header_match.group(1).strip() if header_match else "Unknown Source"

            # Split records by middle dot separator (U+00B7)
            record_separator = "·" * 10  # at least 10 middle dots
            records_raw = re.split(rf"\n\s*{record_separator}.*\n", block)

            for idx, rec in enumerate(records_raw):
                rec = rec.strip()
                if not rec or len(rec) < 10:
                    continue

                # Deep key-value extraction + normalization inside each source record
                data: dict[str, Any] = {}
                for line in rec.splitlines():
                    if ":" in line:
                        k, _, v = line.partition(":")
                        k = k.strip()
                        v = v.strip()
                        if not k or not v:
                            continue

                        k_lower = k.lower()

                        # Smart normalization per key type
                        if any(x in k_lower for x in ["тел", "моб", "phone"]):
                            norm = normalize_phone(v)
                            data[k] = norm or v
                        elif "дата" in k_lower:
                            data[k] = normalize_datetime(v) or v
                        elif any(x in k_lower for x in ["паспорт", "документ"]):
                            data[k] = normalize_passport(v) or v
                        elif "инн" in k_lower:
                            data[k] = normalize_inn(v) or v
                        elif "снилс" in k_lower:
                            data[k] = normalize_snils(v) or v
                        elif "email" in k_lower or "почта" in k_lower:
                            data[k] = v.lower()
                        else:
                            data[k] = v

                findings.append({
                    "source_name": source_name,
                    "record_index": idx,
                    "data": data,
                    "raw_text": rec[:2500],
                })

        return findings

    # ==================== POST-PROCESSING ====================

    def _post_process(self, report: ParsedReport) -> None:
        """
        Fill main_* fields in main_person using frequency analysis + deduplication.
        This runs after all sections have been parsed.
        """
        person = report.main_person

        # Collect candidates from everywhere
        all_phones: list[str] = list(person.phones) + list(person.extra_phones)
        all_emails: list[str] = list(person.emails) + list(person.extra_emails)
        all_passports: list[str] = list(person.passports) + list(person.extra_passports)
        all_inns: list[str] = list(person.extra_inns)
        if person.inn:
            all_inns.append(person.inn)

        # From documents
        for doc in report.documents:
            num = doc.get("number") or doc.get("number_raw", "")
            if num:
                p = normalize_passport(num)
                if p:
                    all_passports.append(p)
                inn = normalize_inn(num)
                if inn:
                    all_inns.append(inn)

        # From source findings (richest source)
        for finding in report.source_findings:
            data = finding.get("data", {})
            for key, val in data.items():
                k = key.lower()
                if any(x in k for x in ["тел", "моб", "phone"]):
                    p = normalize_phone(val)
                    if p: all_phones.append(p)
                elif "email" in k or "почта" in k:
                    all_emails.append(val.lower())
                elif "паспорт" in k:
                    p = normalize_passport(val)
                    if p: all_passports.append(p)
                elif "инн" in k:
                    i = normalize_inn(val)
                    if i: all_inns.append(i)
                elif "снилс" in k and not person.snils:
                    person.snils = normalize_snils(val)

        def most_common(items: list[str]) -> Optional[str]:
            if not items:
                return None
            from collections import Counter
            cleaned = [x for x in items if x]
            return Counter(cleaned).most_common(1)[0][0] if cleaned else None

        # Fill main fields preferring the most frequent values
        person.main_phone = person.main_phone or most_common(all_phones)
        person.main_email = person.main_email or most_common(all_emails)
        person.main_passport = person.main_passport or most_common(all_passports)
        person.main_inn = person.main_inn or most_common(all_inns)

        # Final deduplication
        person.phones = sorted(set(all_phones))
        person.emails = sorted(set(all_emails))
        person.passports = sorted(set(all_passports))
        person.extra_phones = sorted(set(person.extra_phones))
        person.extra_emails = sorted(set(person.extra_emails))
        person.extra_passports = sorted(set(person.extra_passports))
        person.extra_inns = sorted(set(all_inns))
